#!/bin/bash
# This script is under license BEER-WARE
# "THE BEER-WARE LICENSE" (Revision 42):
# <eric@obarun.org> wrote this file.  As long as you retain this notice you
# can do whatever you want with this stuff. If we meet some day, and you think
# this stuff is worth it, you can buy me a beer in return.   Eric Vidal

#shopt -s extglob

sourcing(){
	
	local list
	
	for list in /usr/lib/obarun/common_functions /etc/obarun/pacopts.conf; do
		if [[ -f "${list}" ]]; then
			source "${list}"
		else
			echo_error " Missing file : ${list}"
			exit	
		fi
	done
	
	unset list
}
#sourcing


## 		common functions

usage(){
	cat << EOF
	
${bold}Usage: ${0} [options] [sysusers file name]${reset}

General options:
	origin : check origin of packages
	applysys : wrap up a sysusers file 
	applytmp : wrap up all tmpfiles
EOF
	exit 0
}

##			ORIGIN FUNCTIONS

# ${1} name of the repos to use
find_origin(){
	local ori check ver repo_origin parse_ori parse_ori_repo parse_ori_name parse_ori_version
	
	repo_origin="${1}"
	
	for check in ${both[@]};do 
		
		if [[ "$check" != obarun-@(mkiso|install|build) ]]; then
		
			printf "\r${bold}     -> Check %s package${reset}" "$check"
			tput el #return to the last line
		
			while read ori; do
			
				parse_ori=${ori}
				
				#retrieve only the repo
				parse_ori_repo=${parse_ori%%/*}
			
				# retrieve only the name
				parse_ori_name=${parse_ori##*/}
				parse_ori_name=${parse_ori_name%%' '*}
				
				#retrieve only the version
				#if the value not return a version format then the package do not come from $repo_origin
				if [[ "${parse_ori_name}" == "$check" ]]; then ## avoid search regex on packages description
					parse_ori_version=${parse_ori##*[}
					ver=$(grep ":" <<< "${parse_ori_version}")
					
					if [[ -n "${ver}" ]];then
						parse_ori_version=${parse_ori_version##*' '}
						parse_ori_version=${parse_ori_version%%]*}
					else
						unset parse_ori_version
					fi
					unset ver
				fi
				
				check_var(){
					printf "\n"
					echo ori :: ${ori}
					echo parse_ori :: ${parse_ori}
					echo parse_ori_repo :: ${parse_ori_repo%%/}
					echo parse_ori_name :: ${parse_ori_name}
					echo ver :: ${ver}
					echo parse_ori_version :: ${parse_ori_version}
				}
				#check_var
				
				# version is not empty, the package installed do not come from $repo_origin
				if [[ -n $parse_ori_version ]]; then
					false+=("$check")
				fi
				
				unset parse_ori parse_ori_repo parse_ori_name parse_ori_version
			
			done < <(pacman -Ss "$check" | grep "${repo_origin}")
		fi
	done
	 
	printf "\n${bold}==>> Finished ${reset}\n"

	unset ori check ver repo_origin parse_ori parse_ori_repo parse_ori_name parse_ori_version
}

# ${1} name of the repos to use
# if empty, obarun is set by default
check_package(){
	
	local named item repo
	local -a both false repo_db
	
	# pick obarun by default
	repo="${1:-obarun}"
	
	mapfile -t repo_db < <(pacman -Slq "${repo}")
	
	# FILTER : Compare list of $installed package and $repo database,
	# if exist on twice put it on $both array
		
	while read named;do 
		for item in ${repo_db[@]}; do #$(pacman -Slq obarun)
			if  [[ "$named" == "$item" ]]; then 
				both+=("$item")
			fi
		done
	done < <(pacman -Qsq)
	
	echo_display " Verifying ${repo} packages repository"
	
	#check origin of package
	find_origin "${repo}"
	
	if ! [[ -z "${false[@]}" ]]; then 
		printf "${byellow}==>> These/those package(s) do not come from ${repo} repository :${reset}\n" 
		for no in "${false[@]}"; do
			echo_bold "	-> $no"
		done
		echo_display " Do you want to replace this/those package(s) [y|n]"
		reply_answer
		if (( ! $? )); then
			for i in "${false[@]}"; do
				pacman -S "${repo}"/$i
			done
		fi
	fi
	
	unset named item repo both false repo_db
}



##				SYSUSERS FUNCTION

# ${1} path to the file
# ${2} file to parse, can be a list e.g. "nbd.conf quemu.conf"
parse_file(){
	
	local tidy_loop path_file check parse_check
	local -a named
	
	path_file="${1}"
	named=( "${2}" )
	
	for tidy_loop in ${path_file}/${named[@]}; do
		
		tidy_loop=${tidy_loop##*/}

		while read check; do
	
			while read -d " " parse_check;do 
				case $parse_check in 
					u|g|m|r)
						parse_line "${parse_check}" "${check} "
						;;
					*) continue ;;
				esac
			done <<< "${check}"
	
		done < "${path_file}/${tidy_loop}"
	
	done 
	
	unset named tidy_loop path_file check parse_check
}

# {1} sysusers options : mean u,g,m or r
# {2} complete line to parse
parse_line(){
	 
	opts="${1}"
	line="${2}"
	
	case "${opts}" in
		u) 	line_u		
			;;
		g) 	line_g
			;;
		m) 	line_m
			;;
		r)	line_r
			;;
	esac	
	
	
}

# {1} line to parse
check_args(){
	
	local what element
	what="${1}"

	while read -d " " element; do
		case "${element}" in
			u|g|r) continue 
					;;
			m) 	named_g=$(awk -F " " '{print $2 }' <<< ${what})
				group_g=$(awk -F " " '{print $3 }' <<< ${what})
				;;	
			\"*) comment_=$(awk -F "\"*\"" '{ print $2 }' <<< ${what})
				;;
			*[0-9])
				uidgid="${element}"		
				;;
			/*)
				directory_="${element}"
				;;
			-) 	continue
				;;
			*\") continue
				;;
			*[a-z]|*[A-z])
				echo ${what} | awk -F "${element}" '{ print $1 }' | grep \" &>/dev/null
				if [[ $? -eq 0 ]]; then
					continue
				else
					named_="${element}"
				fi
				;;
		esac
	done <<< "${what}"
	
	unset what element
}

line_u(){
	local named_ directory_ optdirectory_ optdirectory_v uidgid optgid optgid_v optuid optuid_v comment_ optcomment optcomment_v

	check_args "${line}"
	
	if [[ -z "${directory_}" ]]; then
		optdirectory="-d"
		optdirectory_v="/"
	else
		optdirectory="-d"
		optdirectory_v="${directory_}"
	fi
	if [[ -z "${uidgid}" ]]; then
		optgid=""
		optgid_v=""
		optuid=""
		optuid_v=""
	else
		optgid="-g"
		optgid_v="${uidgid}"
		optuid="-u" 
		optuid_v="${uidgid}"
	fi
	if [[ -z "${comment_}" ]]; then
		optcomment=""
		optcomment_v=""
	else
		optcomment="-c" 
		optcomment_v="${comment_}"
	fi
	
	getent group ${named_} &>/dev/null
	if [[ $? -eq 0 ]]; then
		echo_info " group ${named_} already exist, nothing to do"
	else
		echo_display " Creating group ${named_} with the option(s):"
		echo_display " ${optgid} ${optgid_v}" 
		groupadd -r "${optgid}" "${optgid_v}" "${named_}" || die " Impossible to create group ${named_}"
	fi
	
	getent passwd ${named_} &>/dev/null
	if [[ $? -eq 0 ]]; then
		echo_info " user ${named_} already exist, nothing to do"
	else
		echo_display " Creating user ${named_} with the option(s):"
		echo_display " ${optuid} ${optuid_v} ${optgid} ${optgid_v} ${optdirectory} ${optdirectory_v} ${optcomment} ${optcomment_v} -s /sbin/nologin"
		useradd -r "${optuid}" "${optuid_v}" "${optgid}" "${optgid_v}" "${optdirectory}" "${optdirectory_v}" "${optcomment}" "${optcomment_v}" -s /sbin/nologin "${named_}"	|| die " Impossible to create user ${named_}"
	fi
	
	unset named_ directory_ optdirectory_ optdirectory_v uidgid optgid optgid_v optuid optuid_v comment_ optcomment optcomment_v
}
line_g(){
	local uidgid optgid optgid_v optuid optuid_v named_
	
	check_args "${line}"
	
	if [[ -z "${uidgid}" ]]; then
		optgid=""
		optgid_v=""
		optuid=""
		optuid_v=""
	else
		optgid="-g"
		optgid_v="${uidgid}"
		optuid="-u" 
		optuid_v="${uidgid}"
	fi
	
	getent group ${named_} &>/dev/null
	if [[ $? -eq 0 ]]; then
		echo_info " group ${named_} already exist, nothing to do"
	else	
		echo_display " Creating group ${named_} with the option(s):"
		echo_display " ${optgid} ${optgid_v}"
		groupadd -r "${optgid}" "${optgid_v}" "${named_}" || die " Impossible to create group ${named_}"
	fi
	
	unset uidgid optgid optgid_v optuid optuid_v named_
}

line_m(){
	local named_g group_g uidgid optgid optgid_v optuid optuid_v directory_ optdirectory_ optdirectory_v comment_ optcomment optcomment_v
	
	check_args "${line}"
	
	if [[ -z "${directory_}" ]]; then
		optdirectory=""
		optdirectory_v=""
	else
		optdirectory="-d"
		optdirectory_v="${directory_}"
	fi
	
	if [[ -z "${uidgid}" ]]; then
		optgid=""
		optgid_v=""
		optuid=""
		optuid_v=""
	else
		optgid="-g"
		optgid_v="${uidgid}"
		optuid="-u" 
		optuid_v="${uidgid}"
	fi
	
	if [[ -z "${comment_}" ]]; then
		optcomment=""
		optcomment_v=""
	else
		optcomment="-c" 
		optcomment_v="${comment_}"
	fi
	
	getent group ${group_g} &>/dev/null
	if [[ $? -ne 0 ]]; then
		echo_info " group ${group_g} does not exist, create it"
		groupadd -r "${optgid}" "${optgid_v}" "${group_g}" || die " Impossible to create group ${group_g}"
	fi
	
	getent passwd ${named_g} &>/dev/null
	if [[ $? -ne 0 ]]; then
		echo_info " user ${named_g} does not exist, create it"
		echo useradd -r "${optuid}" "${optuid_v}" "${optgid}" "${optgid_v}" "${optdirectory}" "${optdirectory_v}" "${optcomment}" "${optcomment_v}" "${named_g}" || die " Impossible to create user ${named_g}"
	fi
	
	echo_display " Add user ${named_g} to group ${group_g}"
	gpasswd -a "${named_g}" "${group_g}" || die " Impossible to add ${named_g} to group ${group_g}"
	
	unset named_g group_g uidgid optgid optgid_v optuid optuid_v directory_ optdirectory_ optdirectory_v comment_ optcomment optcomment_v
}

line_r(){
	echo_info " Pacopts cannot parse the file ${path_file}/${named} for r line,"
	echo_info " you need to do it manually"
	break
}

##				TMPFILE FUNCTION

tmpfiles(){
	/usr/lib/obarun/tmpfiles.sh --create
}
